<?php

require_once('itcross_test.inc');

function itcross_test_menu() {
  
  $items['itcross/test-script'] = array(
  'title' => 'Test',
  'page callback' => '_itcross_test_script',
  'access arguments' => array('test'),
  'expanded' => TRUE,
  );   

  return $items;
}


function itcross_test_permission() {
  return array(
    'test' => array(
      'description' => t('Run test scripts'),
      'title' => t('Run test scripts of the module.'),
      'restrict access' => TRUE,
    ),

  );
}


